function obj = calc_ADM_obj(rgb_E,dep_E,rgb_Z,dep_Z,rgb_U,dep_U,rgb_J,dep_J,rgb_V,dep_V,rgb_S,dep_S,rgb_W,dep_W,rgb_P,dep_P,param,mu)

    obj = param.lambda11*(norm(rgb_E,'fro')^2+norm(dep_E,'fro')^2)....
        + param.gamma*norm(dep_Z-rgb_Z,'fro')^2....
        + sum(sum(rgb_U.*(rgb_Z-rgb_J))) + sum(sum(dep_U.*(dep_Z-dep_J)))....
        + sum(sum(rgb_V.*(rgb_Z-rgb_S))) + sum(sum(dep_V.*(dep_Z-dep_S)))....
        + sum(sum(rgb_P.*(rgb_W-rgb_W*rgb_S-rgb_E))) + sum(sum(dep_P.*(dep_W-dep_W*dep_S-dep_E)))....
        + mu/2*(norm(rgb_Z-rgb_J,'fro')^2+norm(dep_Z-dep_J,'fro')^2)....
        + mu/2*(norm(rgb_Z-rgb_S,'fro')^2+norm(dep_Z-dep_S,'fro')^2)....  
        + mu/2*(norm(rgb_W-rgb_W*rgb_S-rgb_E,'fro')^2+norm(dep_W-dep_W*dep_S-dep_E,'fro')^2)....
        + param.lambda2*(calc_nuclear_norm(rgb_J)+calc_nuclear_norm(dep_J));
        