function obj = calc_ADM_ori_obj_sim(rgb_Z,dep_Z,rgb_W,dep_W,param)

obj = param.lambda11*(norm(rgb_W-rgb_W*rgb_Z,'fro')^2+norm(dep_W-dep_W*dep_Z,'fro')^2)....
    + param.lambda2*(calc_nuclear_norm(rgb_Z)+calc_nuclear_norm(dep_Z))....
    + param.gamma*(norm(rgb_Z-dep_Z,'fro')^2);
